configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-little-mouse-a2kk1re5-pooler.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_xQAEa2m8BftW
